### PR TITLE
Compile opaleye-sqlite with ghc-8.10.3.

### PR DESCRIPTION
**Pull request by fisx**
It compiles, but I haven't set up a postgresql to run the test suite.

Btw a release of opaleye-sqlite (after this) would be appreciated, but no pressure!  :-)

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Oh, cool, I had no idea that anyone was still using opaleye-sqlite.

> I haven't set up a postgresql

I'm not sure what you mean by that. postgresql should not be required for opaleye-sqlite!

**Comment by tomjaguarpaw** [comment]
Can you really get this to compile with 8.10? I get the error below. In fact I even get it for 8.6.

```
src/Opaleye/SQLite/Internal/HaskellDB/Sql/Print.hs:119:37: error:
    Ambiguous occurrence ‘<>’
    It could refer to
       either ‘Prelude.<>’,
              imported from ‘Prelude’ at src/Opaleye/SQLite/Internal/HaskellDB/Sql/Print.hs:5:8-50
              (and originally defined in ‘GHC.Base’)
           or ‘Text.PrettyPrint.HughesPJ.<>’,
              imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/SQLite/Internal/HaskellDB/Sql/Print.hs:27:53-56
    |
119 |       FunSqlExpr f es     -> text f <> parens (commaH ppSqlExpr es)
    |                                     ^^
```

**Comment by tomjaguarpaw** [comment]
I needed the changes below to build on 8.10. Did you not? If not, how not? I'm puzzled.

https://github.com/tomjaguarpaw/haskell-opaleye/commit/b046d96dab778933f7f5e00bd425151947536d95

**Comment by fisx** [comment]
sorry, my comment about postgres was confusing; i just ran the tests in the repo root in the hope that it would also run tests for opaleye-sqlite, but I see now that's not how it worked.

this is also why i didn't find the errors: i compiled the wrong package.  thanks for the patch, I added it to this branch, fixed teh test suite, and added the sqlite package to the stack.yaml.  (I also tried a cabal.project file, but just putting the `packages` stanza in there doesn't do it.)

btw, stack.yaml should be updated, it produces this error:

```
opaleye             > /home/mf/src/haskell-opaleye/src/Opaleye/Internal/RunQuery.hs:291:54: error:
opaleye             >     Not in scope: ‘PGSR.fromFieldRange’
opaleye             >     Module ‘Database.PostgreSQL.Simple.Range’ does not export ‘fromFieldRange’.
opaleye             >     |
opaleye             > 291 |   QueryRunnerColumn (P.lmap C.unsafeCoerceColumn c) (PGSR.fromFieldRange pff)
opaleye             >     |                                                      ^^^^^^^^^^^^^^^^^^^
opaleye             >  
                       
--  While building package opaleye-0.7.1.0 using:
      /mnt/X/home/mf/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1 build lib:opaleye test:test test:tutorial --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 72/73
```

i think this is unrelated to this PR?

**Comment by tomjaguarpaw** [comment]
Thanks for bringing this up to date! I'm not sure if you have used opaleye-sqlite before, but it is really not maintained these days and has really fallen behind opaleye.

When the following action completes I'll merge the 8.10 branch. I squashed some stuff to make it a bit neater. If you'd like to fix the stack.yml can you make a separate PR? I don't know anything at all about stack.

https://github.com/tomjaguarpaw/haskell-opaleye/actions/runs/486347676

**Comment by tomjaguarpaw** [comment]
I merged a different version of this to master. Thanks!

I didn't include the stack.yml stuff. If you want that in the repo can you submit a separate PR?

**Comment by fisx** [comment]
thanks for cleaning this up, and good idea to make the stack.yaml a separate commit.

and yes, i read somewhere that the sqlite package is not as polished as the postgres one, but good to hear it again from you.  i'm planning to use it for something very small and simple, if i run into any issues you'll hear from me again.
