### PR TITLE
GHC 8.4.2 compatibility

### PR DESCRIPTION
**Pull request by zyla**
Tested locally using `stack` with the following `stack.yaml`:

```yaml
compiler: ghc-8.4.2
resolver: nightly-2018-05-18
allow-newer: true
extra-deps:
- git: https://github.com/lpsmith/postgresql-simple
  commit: 14d00c22713aab7d55a81a81b47cc5bb7280398f
- git: https://github.com/larskuhtz/multiset
  commit: 2f96b22ab3be34a102b0266a3a77033ca5cb349f
```

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks.  Merged as https://github.com/tomjaguarpaw/haskell-opaleye/commit/5377df0219db3d36257e574a242ed8f60442bb6b

**Comment by zyla** [comment]
@tomjaguarpaw Thanks for merging.

I noticed a weird thing: while Travis is reporting the build as passing (https://travis-ci.org/tomjaguarpaw/haskell-opaleye/jobs/380773893), it's actually failing with:

```
Building library for multiset-0.3.3..
[1 of 2] Compiling Data.MultiSet    ( Data/MultiSet.hs, dist/build/Data/MultiSet.o )
Data/MultiSet.hs:188:10: error:
    • Could not deduce (Semigroup (MultiSet a))
        arising from the superclasses of an instance declaration
      from the context: Ord a
        bound by the instance declaration at Data/MultiSet.hs:188:10-37
    • In the instance declaration for ‘Monoid (MultiSet a)’
    |
188 | instance Ord a => Monoid (MultiSet a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

But the `neil` script does a weird thing: it says

```
Failed because some dependencies failed to install, not my fault
```

and exits successfully!

**Comment by tomjaguarpaw** [comment]
I guess `multiset` doesn't compile on 8.4 and furthermore I guess this is the reason that you have a specific commit of the `multiset` repo in your `stack.yaml`.  If there's a failure to build dependencies then `neil` considers this to be not a bug (since it isn't *our* bug).  (I think the latest version of `neil` may have changed this behaviour.)

**Comment by tomjaguarpaw** [comment]
I can't build `opaleye` on 8.4 anyway, because `postgresql-simple` is not 8.4-compatible (which I guess you also know!).
